### ISSUE TITLE
Add CRC checking to database entries

### ISSUE THREAD

**Issue by nthdimtech** [nthdimtech/signet-firmware#2]
Check CRC after each read or write and notify client if the check detects a problem

**Comment by nthdimtech** [comment]
This is covered already by flash ECC checking. Just need to make sure that flash ECC error events are processed correctly

**Comment by dumblob** [comment]
Could you please link here commits which contain the checks for ECC errors and their appropriate handling? I could not find them in the history nor using `grep -ir ecc` on the whole repository.

**Comment by nthdimtech** [comment]
More work on ECC error handling needs to be done, that's why issue #6 is still open. I closed this bug to indicate that I was going to use the MCU flash ECC instead of a software CRC. I presently group all errors that occur during writing together and return WRITE_FAILED to whatever command is active while the write was occurring.  You can see the code for that in flash_l443xc.c where flash_write_failed() is called.
