### ISSUE TITLE
ba6e1d1 breaks compilation of commands.c

### ISSUE THREAD

**Issue by tuxlifan** [nthdimtech/signet-firmware#23]
ba6e1d1 does not compile commands.c
I believe the problem is a missing opening curly brace for the added "if" block on line 970?

Possible fix:
```
--- commands.c.broken   2018-02-23 19:58:08.164552452 +0000
+++ commands.c  2018-02-23 19:58:16.905516576 +0000
@@ -967,7 +967,7 @@
                }
                int uid = data[0] + (data[1] << 8);
                int masked = data[2];
-               if (uid <= MIN_UID || uid > MAX_UID)
+               if (uid <= MIN_UID || uid > MAX_UID){
                        finish_command_resp(INVALID_INPUT);
                        return 0;
                }
```

**Comment by nthdimtech** [comment]
Yes that should fix it.  I can't believe I made that change without compilation testing... I should setup CI for the firmware

**Comment by nthdimtech** [comment]
Just pushed a fix. If you want to update your firmware from source you'll need to run:

./signet-firmware-encoder signet-fw

This will create the "sfw" file the GUI can read
