### ISSUE TITLE
'Password slots' and keyboard layouts

### ISSUE THREAD

**Issue by tuxlifan** [nthdimtech/signet-firmware#28]
What are the plans regarding different keyboard layouts?
IIRC there was some discussion (that I can't seem to find now) about saving the layout for each slot?

**Comment by nthdimtech** [comment]
Yes that is the plan. I'll create an issue for it. Password slots is a new feature and I decided to release it sooner for the benefit of people okay with it as is.

**Comment by tuxlifan** [comment]
For posterity, the mentioned discussion was in https://github.com/nthdimtech/signet-desktop-client/issues/22
Closed,
Thanks.

**Comment by nthdimtech** [comment]
Also for reference there are two issues for this #29 at the firmware level and nthdimtech/signet-desktop-client#82 for the client
