### ISSUE TITLE
Signet writes B instead of A

### ISSUE THREAD

**Issue by garro95** [nthdimtech/signet-firmware#30]
I have this kind of weird problem: all "a"s in my usernames (and I suppose also passwords) are exchanged with "b"s. All other characters are correct.

**Comment by nthdimtech** [comment]
Sounds like a keyboard layout issue. What keyboard layout do you use? Also have you run the keyboard layout detection tool? It's under "file->settings" then look for "keyboard layout". If you've already configured before or the issue persists could you take a screenshot of what you see in the configuration tool?

**Comment by garro95** [comment]
I had a similar problems on another machine. Configuring the keyboard layout several times solved the issue in the end, passing by situations in which it wrote "a " instead of "a" (all a were followed by a white space). I also have another problem sometimes: performing the auto-login fails, while autotyping username and password manually as two operations works. I feel like the typing should be a little slower to solve these issues. It may depend also on my machines: I use Ubuntu 18.04 with the Gnome3 desktop environment and the tests were performed on firefox.
